#使用http协议时，http： server: port: 8080即可
server:
  port: 8080

guns:
  RedisCache: true               #是否开始spring缓存实现为redis true：redis false：EhCache
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  file-upload-path: D:\develop\apache-tomcat-8.5.9\webapps\ROOT\file   #文件上传目录(不配置的话为java.io.tmpdir目录)D:\develop\apache-tomcat-8.5.9\webapps\ROOT\file  &&/usr/local/diruicloud/file
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  main:
    allow-bean-definition-overriding: true


log:
  path: tangx-logs

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootproject?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    filters: wall,mergeStat

#多数据源情况的配置
mpen:
  muti-datasource:
    open: false
    url: jdbc:mysql://127.0.0.1:3306/diruicloud_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    dataSourceNames:
    - dataSourceGuns
    - dataSourceBiz

---
#本地开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootproject?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat
  redis:
    #单机模式
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  typeAliasesPackage: cn.com.mpen.modular.system.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #mybatis-plus配置控制台打印完整带参数SQL语句

---
#本地开发多机环境
spring:
  profiles: dev_multi
  datasource:
    url: jdbc:mysql://localhost:3306/springbootproject?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat
  redis:
    #redis哨兵模式
    sentinel: #哨兵模式根据名称自动选择master
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579

mybatis-plus:
  typeAliasesPackage: cn.com.mpen.modular.system.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #mybatis-plus配置控制台打印完整带参数SQL语句

---
#本地开发控制台无sqlLog
spring:
  profiles: dev_notsqllog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootproject?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat
  redis:
    #单机模式
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  typeAliasesPackage: cn.com.mpen.modular.system.model
